# Generated by Django 4.2.30 on 2026-04-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('run_time', models.TimeField(default='08:00')),
                ('periodic_task_name', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Schedule',
                'verbose_name_plural': 'Student Schedules',
            },
        ),
    ]
